# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: posts_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'posts_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13posts_service.proto\x12\x0bpostservice\x1a\x1fgoogle/protobuf/timestamp.proto\"n\n\x11\x43reatePostRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x17\n\x0f\x63reator_user_id\x18\x03 \x01(\t\x12\x12\n\nis_private\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\"!\n\x0eGetPostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\"f\n\x11UpdatePostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x12\n\nis_private\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\"5\n\x11\x44\x65letePostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"%\n\x12\x44\x65letePostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"2\n\x10ListPostsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08per_page\x18\x02 \x01(\x05\"L\n\x11ListPostsResponse\x12(\n\x05posts\x18\x01 \x03(\x0b\x32\x19.postservice.PostResponse\x12\r\n\x05total\x18\x02 \x01(\x05\"\xda\x01\n\x0cPostResponse\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x17\n\x0f\x63reator_user_id\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nis_private\x18\x07 \x01(\x08\x12\x0c\n\x04tags\x18\x08 \x03(\t2\xfd\x02\n\x0bPostService\x12G\n\nCreatePost\x12\x1e.postservice.CreatePostRequest\x1a\x19.postservice.PostResponse\x12\x41\n\x07GetPost\x12\x1b.postservice.GetPostRequest\x1a\x19.postservice.PostResponse\x12G\n\nUpdatePost\x12\x1e.postservice.UpdatePostRequest\x1a\x19.postservice.PostResponse\x12M\n\nDeletePost\x12\x1e.postservice.DeletePostRequest\x1a\x1f.postservice.DeletePostResponse\x12J\n\tListPosts\x12\x1d.postservice.ListPostsRequest\x1a\x1e.postservice.ListPostsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'posts_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPOSTREQUEST']._serialized_start=69
  _globals['_CREATEPOSTREQUEST']._serialized_end=179
  _globals['_GETPOSTREQUEST']._serialized_start=181
  _globals['_GETPOSTREQUEST']._serialized_end=214
  _globals['_UPDATEPOSTREQUEST']._serialized_start=216
  _globals['_UPDATEPOSTREQUEST']._serialized_end=318
  _globals['_DELETEPOSTREQUEST']._serialized_start=320
  _globals['_DELETEPOSTREQUEST']._serialized_end=373
  _globals['_DELETEPOSTRESPONSE']._serialized_start=375
  _globals['_DELETEPOSTRESPONSE']._serialized_end=412
  _globals['_LISTPOSTSREQUEST']._serialized_start=414
  _globals['_LISTPOSTSREQUEST']._serialized_end=464
  _globals['_LISTPOSTSRESPONSE']._serialized_start=466
  _globals['_LISTPOSTSRESPONSE']._serialized_end=542
  _globals['_POSTRESPONSE']._serialized_start=545
  _globals['_POSTRESPONSE']._serialized_end=763
  _globals['_POSTSERVICE']._serialized_start=766
  _globals['_POSTSERVICE']._serialized_end=1147
# @@protoc_insertion_point(module_scope)
